<?php
   		$cidades = [
	["imagem" => "imagens/saopaulo.png",
	"titulo" => "São Paulo",
	"qtd_pts" => "8 pontos cadastrados",
	"link" => "cidades/saopaulo.php"],
	["imagem" => "imagens/riodejaneiro.png",
	"titulo" => "Rio de Janeiro",
	"qtd_pts" => "10 pontos cadastrados",
	"link" => "cidades/riodejaneiro.php"],
	["imagem" => "imagens/brasilia.png",
	"titulo" => "Brasília",
	"qtd_pts" => "4 pontos cadastrados",
	"link" => "cidades/brasilia.php"],
	["imagem" => "imagens/fortaleza.png",
	"titulo" => "Fortaleza",
	"qtd_pts" => "6 pontos cadastrados",
	"link" => "cidades/fortaleza.php"],
	["imagem" => "imagens/salvador.png",
	"titulo" => "Salvador",
	"qtd_pts" => "6 pontos cadastrados",
	"link" => "cidades/salvador.php"],
	["imagem" => "imagens/belohorizonte.png",
	"titulo" => "Belo Horizonte",
	"qtd_pts" => "5 pontos cadastrados",
	"link" => "cidades/belohorizonte.php"],
	["imagem" => "imagens/manaus.png",
	"titulo" => "Manaus",
	"qtd_pts" => "6 pontos cadastrados",
	"link" => "cidades/manaus.php"],
	["imagem" => "imagens/curitiba.png",
	"titulo" => "Curitiba",
	"qtd_pts" => "6 pontos cadastrados",
	"link" => "cidades/curitiba.php"],
	["imagem" => "imagens/recife.png",
	"titulo" => "Recife",
	"qtd_pts" => "4 pontos cadastrados",
	"link" => "cidades/recife.php"],
	["imagem" => "imagens/goiania.png",
	"titulo" => "Goiânia",
	"qtd_pts" => "8 pontos cadastrados",
	"link" => "cidades/goiania.php"]
	];

?>